{% set name = "Collectfast" %}
{% set version = "0.6.2" %}
{% set sha256 = "fe6d811b25865bef5ae3b39c64b0d38776843f77a6d949ae449317afe84ed570" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - django >=1.8
    - django-storages

test:
  imports:
    - collectfast

about:
  home: https://github.com/jazzband/collectfast
  license: MIT
  license_family: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'A Faster Collectstatic '
  description: |
    The fast collectstatic for Django projects with S3 as storage backend.
  doc_url: https://github.com/jazzband/collectfast
  dev_url: https://github.com/jazzband/collectfast

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
