travis:
  secure:
    BINSTAR_TOKEN: P+3fuQ6GYp9TM57PESd8k9mvLc6SGLeSEmvdJhiDPpZwsEJuHBYQ8AlUHP/IJ/LZxiJhKUodDXUOJY2NGhyqG7tfHPk4fAt88SYqGWCYV+G/vBmsxm4Yz6w/vd80Q/8BJh4LOtHu+gS2ve0Ikie7S696RRHTJD2NuNNpG0CJ/fgGV4kjHWB4ulBwYEuC0KrAu28cVWu9BFoppOwkYXqCDow8p+jE/6rgHz1HA3HvFH7YkF8+pnD+KYe3CMwdF5168kCehDKvf9qBmTSvnphfltvEjBRyupWmejZXFOIBv5OVconUgel0p2mZzaaQXo3f1q4VU6JUFx721uWlDIiNnL117gHUnkKRv4LBFIk4Q5s7XxuFF1kAl2IS4SW1nwN88BKxSFmuGg9Tr50mzqqm8XX4zlCugn9YQ1OdXfk+RjyW16SyuZUTu2kdDGNQjgu91sbap+ZzkHiQf0NB9mayTzGlKFfOmPh8ik1O8p1k9For442wJnhw3WLHJQ96HZrr5pUyBbZ8bexizxAmvEGxQqQBZ4fRQva7nBvo5otm4RTFfQCaqul1TkP42KctYRaPBqFlhCyUDDu3tO2ps/q6mSIILO3YnRVb3gfBcpXjpqVie7JOBjv8NoAPw8g9nM3thm5BDG2UWnbjOSnnJBzW0QhKqSOjY8zHRPesJLWvWhs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
