travis:
  secure:
    BINSTAR_TOKEN: Rvq/G7CPOi/zctCfuZx88cK19PXXQTtWuYOgW///8a7mNsguvfz4ahBGBAICYLwQ7E1ZxvqAtIYWWdgHrKGpKBBpoZkeSvd8EtxFsGrWLvHkoqVFcAvKI5d1tSeerb2xj5eGPSzsewvuKd+C6Qb9v41xKf2QtcRB+mYlZ8M9LVPSnTxUOZ6qYHqOm2jSlYWZzTnAtiSkulQvji5gLGfdB2lKzIx9YjcC/yTSxAgApbspRO2WfQ7NhXK5B+swdWC2b3L46fNImy6Q8eK6AdW8zUnO6UDlvkd2+RwEg1x12tlo8fr9BpfwPsdzNkONlgmUQ7FxpBdYpANRzFygcEDx2mm1F4YrHMcYRie9TcY472t2mNwnrS60qzVu+yjkCT7hCmaIMVCDTxI10vBFnsJBfC0zw3DFBtPfIUWiVpHjRTuyf2Xrg3qbp9N/1jieJCBuJVCbizZSMlgxnro0//ycClEDcEika1pQkFzAP/HPewGUz1GrpWJONPDcAPcZuGN+E4gGP81LYlTayFQKfAb8oo6dRkUQWgHJJ8nNAjvzymMcYsIiTueqItT6ESpVzYXZDiyekcBaMC9QQyT4FxYCYXQAq5JrpVjuOl8i/l473VYCqlBdvUStYDnwYKzv5FMsQjo7wfZwRwBvgAoyWLBvJXc/yy0qjze9UlEvcwC3G+c=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
