travis:
  secure:
    BINSTAR_TOKEN: uy1VL+p5URNohfrHk+FunXTR+nuidn/T8/KCZkkMgN0zzrMozRiT8qqez3Ko9sxSAxahiA9r3eS3LYEYbzK8hKQPGjWS46Ih6WVAVIG38KJg9CInQYhWr3n10tT35nutfpmE6rayA/DUsVqKWGdTI8/KTj+WlS3xNtfJrGrwI/JPqB9ohT0Lpf3aHjBMtPnEdD3YZ9YqkADIXz6ocFxt7RR1ZQloG6AMlHQ3D+JCNSb48TQn2y8JIT30h4z8QaWmeX8FbRqJYeyzjYVDXERMXdYVlod9wGv8m4ljZjIRRTYMZH/YcnqydueXzZuyKANhuRL1jnF4ilG2PAYIf6X/t9wqDFFQccQDkPvWaXtMpMvKaHzoVZsbiXHroFHBhYwQCXhH0tabfevglexI6uT3tmgPw2Grwkl3rYgI+AsuZ8pz8nKYJHu/fB0sbfFSoAuHZfhFdZ6ydKUYprCAR/DGov7NNG1klUxYmlp1E1OGhOvQ3W5zZObmzRHEIDwTA01K42ArfqTrdIejWduObcOuFYYCzaEgtxnITWNl/Q2B1RixqkDL8pMGdnKfB0Ej4u0ydJS8kekMjbY/SOxLT961uYxAyrDWCyQhtmluTI1QUwrlPDeQypQJu7HAMROhcziqYGG5ufMVDRvn9J54E0PLjjtgx307QPR4AWtI4tkfIFU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
