travis:
  secure:
    BINSTAR_TOKEN: Uid5lz46CrWjBnlNykDrwe82EtZuBEIO+Cy3b1fK/f9TEYLEdhTCRfHsPIiMiV/yUtens1HpPDuUYbZHtZqNySvu/CAMPF35izgMoGgFtgUELPkJWkhWurDEWEFphdKHfGbefTUkYKcqug3FhpyE2zV5CY8TgRl7uVzQdY1VzDyicnQjCGc9e+YVhTyGp548RSDYAKj0tiJA4+6j8dXACTeW7o7Tvc5jOdt8XLA6urKkaaXAX6t1zReR/j3hp81K0860o0LDwd7Nr3UCmubTeSQi4jYA5CPgZlF3WOE5pYGAUJVGOe2HTQp4XWfznnyFvKNr0EX9H57/jlEU1fgjti2JlQ8719+ibV50l6eocTM71ux/hLUzm5BeCyj4rpsGctb+Zr2Mn68V6dGp/fm2wb16eEwXZQIhvVuNm510tkvfHKkeYRQ5SOWc2MlYDmECIK34isPdPyuesxGsteiw/g/Zm3lzGevoS3uVCttBF7jVEE8Bz0uHJuC9aFvR8P5aglQET162EZ5+dL461cmvQ6E3JajodJTdAp2AqJUCL6gLBYTvY8uPWNsm1yBVxXwSs2EwMfcPtBLflSubFxzJqd+4SIaP1YyGmEmGTu8l77ixphkgrJu9FPklkQRzP6zjf0ugsjkF25wEdYFthU1vye6YSUr0vq6Bx8uVMDGeoOc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
